### ISSUE TITLE
scenic.core.errors.ScenicParseError: invalid syntax. Perhaps you forgot 'new'?

### ISSUE THREAD

**Issue by caixxuan** [trust-ai/SafeBench#12]
when I type:
python scripts/run.py --agent_cfg sac.yaml --scenario_cfg scenic.yaml --num_scenario 1 --mode train_scenario

I got a issue:
scenic.core.errors.ScenicParseError: invalid syntax. Perhaps you forgot 'new'?

**Comment by caixxuan** [comment]
Traceback (most recent call last):
  File "scripts/run.py", line 78, in <module>
    runner.run()
  File "/home/oem/SafeBench/safebench/scenic_runner.py", line 327, in run
    self._init_scenic(config)
  File "/home/oem/SafeBench/safebench/scenic_runner.py", line 142, in _init_scenic
    self.scenic = ScenicSimulator(config.scenic_file, self.scenario_config)
  File "/home/oem/SafeBench/safebench/util/scenic_utils.py", line 131, in __init__
    self.scenario = errors.callBeginningScenicTrace(
  File "/home/oem/SafeBench/Scenic/src/scenic/core/errors.py", line 282, in callBeginningScenicTrace
    return func()
  File "/home/oem/SafeBench/safebench/util/scenic_utils.py", line 132, in <lambda>
    lambda: translator.scenarioFromFile(self.args.scenicFile,
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/translator.py", line 142, in scenarioFromFile
    return _scenarioFromStream(
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/translator.py", line 172, in _scenarioFromStream
    compileStream(stream, namespace, compileOptions, filename)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/translator.py", line 289, in compileStream
    scenic_tree = parse_string(source, "exec", filename=filename)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 107, in parse_string
    return parser.parse(mode if mode == "eval" else "file")
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 149, in parse
    res = getattr(self, rule)()
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 586, in file
    (a := self.statements(),)
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 667, in statements
    (a := self._loop1_4())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 10474, in _loop1_4
    (statement := self.statement())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 693, in statement
    (a := self.simple_stmts())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 736, in simple_stmts
    (a := self.simple_stmt())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 786, in simple_stmt
    (assignment := self.assignment())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 1140, in assignment
    (b := self._tmp_18())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 10695, in _tmp_18
    (star_expressions := self.star_expressions())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 4465, in star_expressions
    (a := self.star_expression())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 4507, in star_expression
    (expression := self.expression())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 4338, in expression
    (self.invalid_scenic_instance_creation())
  File "/home/oem/anaconda3/envs/safebench/lib/python3.8/site-packages/pegen/parser.py", line 66, in memoize_wrapper
    tree = method(self, *args)
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 8763, in invalid_scenic_instance_creation
    return self . raise_syntax_error_known_range ( "invalid syntax. Perhaps you forgot 'new'?" , n , s );
  File "/home/oem/SafeBench/Scenic/src/scenic/syntax/parser.py", line 527, in raise_syntax_error_known_range
    raise self._build_syntax_error(message, start, end)
scenic.core.errors.ScenicParseError: invalid syntax. Perhaps you forgot 'new'?
sac.yaml scenic.yaml failed!

**Comment by javyduck** [comment]
Hi,

Apologies for the delayed response. I doubt it is due to the version of Scenic?

But I would prefer to try running the Scenic script from my updated repository for Scenic at https://github.com/javyduck/ChatScene? The environment settings are the same, and I will keep updating that repo for Scenic intergration, so feel free to have a try.

**Comment by pranavreddy23** [comment]
Hi ,

I have the similar issue working on scenic. I tried changing version of scenic ,even building from source. Any idea on what could be the issue?
`scenic.core.errors.ScenicParseError: invalid syntax. Perhaps you forgot 'new'?
`
