### ISSUE TITLE
AttributeError: 'PerceptionScenario' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by wang1528186571** [trust-ai/SafeBench#14]
>> ----------------------------------------
>> Logging data to /home/wang/Desktop/wjl-project/SafeBench-main/log/exp/exp_basic_od_seed_0/progress.txt
>> Evaluation Mode, skip config saving
>> Loading existing record fail because no records.pkl is found.
>> Agent Policy: basic
>> Scenario Policy: od
>> ----------------------------------------
>> Parsing scenario route and data
>> Selecting scenario_id: 3
>> Loading 4 data
>> Parsing 4 unfinished data
>> Initializing carla world: Town_Safebench_Heavy
WARNING: cannot parse georeference: ''. Using default values. 
>> Initializing pygame birdeye renderer
WARNING: cannot parse georeference: ''. Using default values. 
>> Drawing the map of the entire town. This may take a while...
>> Loading scenario data id: 8
Traceback (most recent call last):
  File "scripts/run.py", line 78, in <module>
    runner.run()
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/carla_runner.py", line 333, in run
    self.eval(data_loader)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/carla_runner.py", line 254, in eval
    obs, infos = self.env.reset(sampled_scenario_configs, scenario_init_action)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/env_wrapper.py", line 67, in reset
    obs, info = self.env_list[s_i].reset(config=config, env_id=s_i, scenario_init_action=scenario_init_action[s_i])
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/env_wrapper.py", line 177, in reset
    obs, info = self._env.reset(**kwargs)
  File "/home/wang/anaconda3/envs/safebench/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/envs/carla_env.py", line 218, in reset
    self._create_scenario(config, env_id)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/envs/carla_env.py", line 147, in _create_scenario
    scenario = PerceptionScenario(
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/scenario/scenario_definition/perception_scenario.py", line 43, in __init__
    self.route, self.ego_vehicle, scenario_definitions = self._update_route_and_ego(timeout=self.timeout)
AttributeError: 'PerceptionScenario' object has no attribute 'timeout'
basic.yaml object_detection_pedestrian.yaml failed!
Traceback (most recent call last):
  File "scripts/run.py", line 78, in <module>
    runner.run()
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/carla_runner.py", line 333, in run
    self.eval(data_loader)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/carla_runner.py", line 254, in eval
    obs, infos = self.env.reset(sampled_scenario_configs, scenario_init_action)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/env_wrapper.py", line 67, in reset
    obs, info = self.env_list[s_i].reset(config=config, env_id=s_i, scenario_init_action=scenario_init_action[s_i])
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/env_wrapper.py", line 177, in reset
    obs, info = self._env.reset(**kwargs)
  File "/home/wang/anaconda3/envs/safebench/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 18, in reset
    return self.env.reset(**kwargs)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/envs/carla_env.py", line 218, in reset
    self._create_scenario(config, env_id)
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/gym_carla/envs/carla_env.py", line 147, in _create_scenario
    scenario = PerceptionScenario(
  File "/home/wang/Desktop/wjl-project/SafeBench-main/safebench/scenario/scenario_definition/perception_scenario.py", line 43, in __init__
    self.route, self.ego_vehicle, scenario_definitions = self._update_route_and_ego(timeout=self.timeout)
AttributeError: 'PerceptionScenario' object has no attribute 'timeout'

**Comment by jingzhengli** [comment]
I also met this error, did you solve it?
